/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.popUps.Ventas.Registrar;

import UI.main.Conexion;
import UI.main.mainFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author momo
 */
public class frameRegistrarVenta extends javax.swing.JFrame {

    /**
     * Creates new form frameRegistrarLibro
     */
    public frameRegistrarVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnConfirmarRegistro = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblRutCliente = new javax.swing.JLabel();
        txtRutCliente = new javax.swing.JTextField();
        lblRutTrabajador = new javax.swing.JLabel();
        txtRutTrabajador = new javax.swing.JTextField();
        lblTipoVenta = new javax.swing.JLabel();
        cbxTipoVenta = new javax.swing.JComboBox<>();
        lblMetodoPago = new javax.swing.JLabel();
        cbxMetodoPago = new javax.swing.JComboBox<>();
        lblGuia2 = new javax.swing.JLabel();
        lblImportante = new javax.swing.JLabel();
        lblGuia3 = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(46, 49, 49));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarRegistro.setText("Confirmar registro");
        btnConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRegistroActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registrar Venta:");

        lblRutCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRutCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblRutCliente.setText("RUT Cliente:");

        txtRutCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblRutTrabajador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRutTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblRutTrabajador.setText("RUT Trabajador:");

        lblTipoVenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTipoVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoVenta.setText("Tipo de Venta:");

        cbxTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un método de venta", "Boleta", "Factura" }));

        lblMetodoPago.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMetodoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblMetodoPago.setText("Método de Pago:");

        cbxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un método de pago", "Efectivo", "Crédito", "Débito" }));

        lblGuia2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGuia2.setForeground(new java.awt.Color(255, 255, 255));
        lblGuia2.setText("- Para poder registrar una venta el cliente debe estar registrado");

        lblImportante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblImportante.setForeground(new java.awt.Color(255, 255, 255));
        lblImportante.setText("Importante:");

        lblGuia3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGuia3.setForeground(new java.awt.Color(255, 255, 255));
        lblGuia3.setText("  previamente en la Base de Datos, al igual que el trabajador.");

        lblNumeroSerie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie.setText("Numero de serie del libro:");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImportante)
                            .addComponent(lblGuia2)
                            .addComponent(lblGuia3))
                        .addGap(31, 66, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmarRegistro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                        .addComponent(lblMetodoPago)
                                        .addGap(49, 49, 49))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                        .addComponent(lblTipoVenta)
                                        .addGap(63, 63, 63))
                                    .addComponent(lblNumeroSerie)
                                    .addComponent(lblRutTrabajador)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(lblRutCliente)
                                        .addGap(75, 75, 75)))
                                .addGap(39, 39, 39)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTipoVenta, 0, 200, Short.MAX_VALUE)
                                    .addComponent(txtNumeroSerie)
                                    .addComponent(txtRutTrabajador)
                                    .addComponent(txtRutCliente))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblImportante)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(lblGuia2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGuia3)
                        .addGap(30, 30, 30)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRutCliente)
                            .addComponent(txtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblRutTrabajador))
                    .addComponent(txtRutTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumeroSerie)
                    .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoVenta)
                    .addComponent(cbxTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodoPago)
                    .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnConfirmarRegistro))
                .addContainerGap())
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Back to main Frame
        mainFrame mainF = new mainFrame();
        mainF.setVisible(true);
        mainF.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRegistroActionPerformed
        boolean send = true;
        
        //Fecha actual - Current date
        Date date = new Date();  
        SimpleDateFormat currentY = new SimpleDateFormat("yyyy"); 
        SimpleDateFormat currentM = new SimpleDateFormat("MM"); 
        SimpleDateFormat currentD = new SimpleDateFormat("dd");
        
        String stringCurrentY = currentY.format(date);
        String stringCurrentM = currentM.format(date);
        String stringCurrentD = currentD.format(date);

        String rutCliente = txtRutCliente.getText();
        String rutTrabajador = txtRutTrabajador.getText();
        String tipoVenta = cbxTipoVenta.getSelectedItem().toString();
        String metodoPago = cbxMetodoPago.getSelectedItem().toString();
        String numeroSerie = txtNumeroSerie.getText();
        
        
        try {
            int intNumeroSerie = Integer.parseInt(numeroSerie);
            
        } catch (Exception e) {
            System.out.println("ERROR:" + e.toString());
            send = false;
        }
        //Verificacion de casillas.
        if(rutCliente.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Rellene la casilla RUT Cliente.");
            System.out.println("Casilla RUT Cliente no rellenada.");
            send = false;
        }
        if(rutTrabajador.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Rellene la casilla RUT Trabajador.");
            System.out.println("Casilla RUT Trabajador no rellenada.");
            send = false;
        }
        if(tipoVenta.equalsIgnoreCase("seleccione un método de venta")){
            JOptionPane.showMessageDialog(null, "Ingrese un tipo de venta.");
            System.out.println("No se ingresó un tipo de venta.");
            send = false;
        }
        if(metodoPago.equalsIgnoreCase("seleccione un método de pago")){
            JOptionPane.showMessageDialog(null, "Ingrese un metodo de pago.");
            System.out.println("No se ingresó un metodo de pago.");
            send = false;
        }
        
        
        
        if(send){
        System.out.println("PRINT VALUES:");
        System.out.println("-------------------");
        System.out.println("RUT Cliente " + rutCliente);
        System.out.println("RUT Trabajador: " + rutTrabajador);
        System.out.println("Tipo de Venta: " + tipoVenta);
        System.out.println("Metodo de pago: " + metodoPago);
        System.out.println("Fecha Actual: " + stringCurrentY + "-" + stringCurrentM+ "-" + stringCurrentD);
        System.out.println("");
            
            
        String query = " INSERT INTO VENTA(FECHA_VENTA, FK1_NUMERO_SERIE, FK1_RUT_CLIENTE, FK1_RUT_TRABAJADOR, METODO_PAGO, TIPO_VENTA)"
                    + " values(?, ?, ?, ?, ?, ?)";
       
        try {
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();

            //Creates the statement to connect it to the DB
            PreparedStatement preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1, stringCurrentY + "-" + stringCurrentM + "-" + stringCurrentD);
                    preparedStmt.setInt(2, Integer.parseInt(numeroSerie));
                    preparedStmt.setString(3, rutCliente);
                    preparedStmt.setString(4, rutTrabajador);
                    preparedStmt.setString(5, metodoPago);
                    preparedStmt.setString(6, tipoVenta);
                    
                   

                    preparedStmt.execute();
                    conn.close();
                    JOptionPane.showMessageDialog(null, "Acción realizada con exito.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fatal Error.");
            System.out.println("ERROR: " + e.toString());
        }

        }
        else{
            JOptionPane.showMessageDialog(null, "Casillas mal rellenadas.");
            System.out.println("---------------------------");
            System.out.println("No se concreto la conexion");
            System.out.println("---------------------------");
        }
    }//GEN-LAST:event_btnConfirmarRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameRegistrarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnConfirmarRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxMetodoPago;
    private javax.swing.JComboBox<String> cbxTipoVenta;
    private javax.swing.JLabel lblGuia2;
    private javax.swing.JLabel lblGuia3;
    private javax.swing.JLabel lblImportante;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblRutCliente;
    private javax.swing.JLabel lblRutTrabajador;
    private javax.swing.JLabel lblTipoVenta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtRutCliente;
    private javax.swing.JTextField txtRutTrabajador;
    // End of variables declaration//GEN-END:variables
}
