/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.main;

import UI.popUps.Arriendos.Borrar.frameBorrarArriendo;
import UI.popUps.Arriendos.Registrar.frameRegistrarArriendo;
import UI.popUps.Clientes.Borrar.frameBorrarCliente;
import UI.popUps.Clientes.Registrar.frameRegistrarCliente;
import UI.popUps.Libros.Borrar.ISBN.frameBorrarISBN;
import UI.popUps.Libros.Borrar.Libro.frameBorrarLibro;
import UI.popUps.Libros.Registrar.ISBN.frameRegistrarISBN;
import UI.popUps.Libros.Registrar.Libro.frameRegistrarLibro;
import UI.popUps.Trabajadores.Borrar.frameBorrarTrabajador;
import UI.popUps.Trabajadores.Registrar.frameRegistrarTrabajador;
import UI.popUps.Ventas.Borrar.frameBorrarVenta;
import UI.popUps.Ventas.Registrar.frameRegistrarVenta;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author momo
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Background = new javax.swing.JPanel();
        tbdPanel = new javax.swing.JTabbedPane();
        mainpnlLibros = new javax.swing.JPanel();
        tituloLibros = new javax.swing.JLabel();
        lblSelect = new javax.swing.JLabel();
        pnlInner = new javax.swing.JTabbedPane();
        pnlISBN = new javax.swing.JPanel();
        btnRegistrarLibro1 = new javax.swing.JButton();
        btnBorrarLibro1 = new javax.swing.JButton();
        scrollLibros1 = new javax.swing.JScrollPane();
        tblISBN = new javax.swing.JTable();
        btnUpdateISBN = new javax.swing.JButton();
        pnlOptionsLibro = new javax.swing.JPanel();
        btnRegistrarLibro = new javax.swing.JButton();
        btnBorrarLibro = new javax.swing.JButton();
        scrollLibros = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnUpdateTableLibros = new javax.swing.JButton();
        pnlVentas = new javax.swing.JPanel();
        tituloVentas = new javax.swing.JLabel();
        lblSelect2 = new javax.swing.JLabel();
        btnRegistrarVenta = new javax.swing.JButton();
        btnBorrarVenta = new javax.swing.JButton();
        scrollVentas = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnUpdateTableVentas = new javax.swing.JButton();
        pnlArriendo = new javax.swing.JPanel();
        tituloArriendos = new javax.swing.JLabel();
        lblSelect3 = new javax.swing.JLabel();
        btnRegistrarArriendo = new javax.swing.JButton();
        btnBorrarArriendo = new javax.swing.JButton();
        scrollArriendo = new javax.swing.JScrollPane();
        tblArriendos = new javax.swing.JTable();
        btnUpdateTableArriendo = new javax.swing.JButton();
        pnlClientes = new javax.swing.JPanel();
        tituloClientes = new javax.swing.JLabel();
        lblSelect4 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnBorrarCliente = new javax.swing.JButton();
        scrollCliente = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnUpdateTableClientes = new javax.swing.JButton();
        pnlTrabajadores = new javax.swing.JPanel();
        tituloTrabajadores = new javax.swing.JLabel();
        lblSelect5 = new javax.swing.JLabel();
        btnRegistrarTrabajador = new javax.swing.JButton();
        btnBorrarTrabajador = new javax.swing.JButton();
        scrollTrabajadores = new javax.swing.JScrollPane();
        tblTrabajadores = new javax.swing.JTable();
        btnUpdateTableTrabajador = new javax.swing.JButton();
        logoFastDevelopment = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(46, 49, 49));

        tbdPanel.setBackground(new java.awt.Color(228, 241, 254));
        tbdPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tbdPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbdPanel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        mainpnlLibros.setBackground(new java.awt.Color(218, 223, 225));
        mainpnlLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tituloLibros.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tituloLibros.setText("Opciones de Libros:");

        lblSelect.setText("Seleccione una opción");

        pnlInner.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnRegistrarLibro1.setText("Registrar ISBN");
        btnRegistrarLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibro1ActionPerformed(evt);
            }
        });

        btnBorrarLibro1.setText("Borrar ISBN");
        btnBorrarLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarLibro1ActionPerformed(evt);
            }
        });

        tblISBN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Categoria", "Idioma", "Autor", "Editorial", "Titulo", "Numero de Paginas", "Fecha de Publicacion"
            }
        ));
        scrollLibros1.setViewportView(tblISBN);

        btnUpdateISBN.setText("Actualizar tabla");
        btnUpdateISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateISBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlISBNLayout = new javax.swing.GroupLayout(pnlISBN);
        pnlISBN.setLayout(pnlISBNLayout);
        pnlISBNLayout.setHorizontalGroup(
            pnlISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlISBNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollLibros1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(pnlISBNLayout.createSequentialGroup()
                        .addComponent(btnRegistrarLibro1)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarLibro1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlISBNLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateISBN)))
                .addContainerGap())
        );
        pnlISBNLayout.setVerticalGroup(
            pnlISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlISBNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlISBNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarLibro1)
                    .addComponent(btnBorrarLibro1))
                .addGap(18, 18, 18)
                .addComponent(scrollLibros1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateISBN)
                .addGap(6, 6, 6))
        );

        pnlInner.addTab("ISBN", pnlISBN);

        btnRegistrarLibro.setText("Registrar libro");
        btnRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarLibroActionPerformed(evt);
            }
        });

        btnBorrarLibro.setText("Borrar libro");
        btnBorrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarLibroActionPerformed(evt);
            }
        });

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Serie", "Precio", "IVA", "Distribuidor", "ISBN", "Precio total"
            }
        ));
        scrollLibros.setViewportView(tblLibros);

        btnUpdateTableLibros.setText("Actualizar tabla");
        btnUpdateTableLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOptionsLibroLayout = new javax.swing.GroupLayout(pnlOptionsLibro);
        pnlOptionsLibro.setLayout(pnlOptionsLibroLayout);
        pnlOptionsLibroLayout.setHorizontalGroup(
            pnlOptionsLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(pnlOptionsLibroLayout.createSequentialGroup()
                        .addComponent(btnRegistrarLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarLibro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOptionsLibroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateTableLibros)))
                .addContainerGap())
        );
        pnlOptionsLibroLayout.setVerticalGroup(
            pnlOptionsLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarLibro)
                    .addComponent(btnBorrarLibro))
                .addGap(18, 18, 18)
                .addComponent(scrollLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateTableLibros)
                .addGap(6, 6, 6))
        );

        pnlInner.addTab("Libros", pnlOptionsLibro);

        javax.swing.GroupLayout mainpnlLibrosLayout = new javax.swing.GroupLayout(mainpnlLibros);
        mainpnlLibros.setLayout(mainpnlLibrosLayout);
        mainpnlLibrosLayout.setHorizontalGroup(
            mainpnlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpnlLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainpnlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInner)
                    .addGroup(mainpnlLibrosLayout.createSequentialGroup()
                        .addGroup(mainpnlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLibros)
                            .addComponent(lblSelect))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainpnlLibrosLayout.setVerticalGroup(
            mainpnlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpnlLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLibros)
                .addGap(18, 18, 18)
                .addComponent(lblSelect)
                .addGap(18, 18, 18)
                .addComponent(pnlInner)
                .addGap(45, 45, 45))
        );

        tbdPanel.addTab("Libros", mainpnlLibros);

        pnlVentas.setBackground(new java.awt.Color(218, 223, 225));

        tituloVentas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tituloVentas.setText("Ventas:");

        lblSelect2.setText("Seleccione una opción");

        btnRegistrarVenta.setText("Registrar venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        btnBorrarVenta.setText("Borrar venta");
        btnBorrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarVentaActionPerformed(evt);
            }
        });

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID de Venta", "Fecha de Venta", "Cod. serie del Libro", "RUT Cliente", "RUT Trabajador"
            }
        ));
        scrollVentas.setViewportView(tblVentas);

        btnUpdateTableVentas.setText("Actualizar tabla");
        btnUpdateTableVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateTableVentas))
                    .addGroup(pnlVentasLayout.createSequentialGroup()
                        .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloVentas)
                            .addComponent(lblSelect2)
                            .addGroup(pnlVentasLayout.createSequentialGroup()
                                .addComponent(btnRegistrarVenta)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrarVenta)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloVentas)
                .addGap(18, 18, 18)
                .addComponent(lblSelect2)
                .addGap(18, 18, 18)
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVenta)
                    .addComponent(btnBorrarVenta))
                .addGap(18, 18, 18)
                .addComponent(scrollVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateTableVentas)
                .addGap(88, 88, 88))
        );

        tbdPanel.addTab("Ventas", pnlVentas);

        pnlArriendo.setBackground(new java.awt.Color(218, 223, 225));

        tituloArriendos.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tituloArriendos.setText("Arriendos:");

        lblSelect3.setText("Seleccione una opción");

        btnRegistrarArriendo.setText("Registrar un nuevo arriendo");
        btnRegistrarArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarArriendoActionPerformed(evt);
            }
        });

        btnBorrarArriendo.setText("Borrar un arriendo");
        btnBorrarArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarArriendoActionPerformed(evt);
            }
        });

        tblArriendos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Arriendo", "Costo del Arriendo", "Fecha de Arriendo", "Dias arrendado", "Fecha Entrega", "RUT Cliente", "RUT Trabajador", "Codigo del Libro"
            }
        ));
        scrollArriendo.setViewportView(tblArriendos);

        btnUpdateTableArriendo.setText("Actualizar tabla");
        btnUpdateTableArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableArriendoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArriendoLayout = new javax.swing.GroupLayout(pnlArriendo);
        pnlArriendo.setLayout(pnlArriendoLayout);
        pnlArriendoLayout.setHorizontalGroup(
            pnlArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArriendoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(pnlArriendoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateTableArriendo))
                    .addGroup(pnlArriendoLayout.createSequentialGroup()
                        .addGroup(pnlArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloArriendos)
                            .addComponent(lblSelect3)
                            .addGroup(pnlArriendoLayout.createSequentialGroup()
                                .addComponent(btnRegistrarArriendo)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrarArriendo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlArriendoLayout.setVerticalGroup(
            pnlArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArriendoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloArriendos)
                .addGap(18, 18, 18)
                .addComponent(lblSelect3)
                .addGap(18, 18, 18)
                .addGroup(pnlArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarArriendo)
                    .addComponent(btnBorrarArriendo))
                .addGap(18, 18, 18)
                .addComponent(scrollArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateTableArriendo)
                .addGap(88, 88, 88))
        );

        tbdPanel.addTab("Arriendos", pnlArriendo);

        pnlClientes.setBackground(new java.awt.Color(218, 223, 225));

        tituloClientes.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tituloClientes.setText("Clientes:");

        lblSelect4.setText("Seleccione una opción");

        btnRegistrarCliente.setText("Registrar un cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnBorrarCliente.setText("Borrar cliente");
        btnBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClienteActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT cliente", "Nombre", "Apellido Paterno", "Direccion", "Telefono", "Correo", "Fecha de Nacimiento"
            }
        ));
        scrollCliente.setViewportView(tblClientes);

        btnUpdateTableClientes.setText("Actualizar tabla");
        btnUpdateTableClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateTableClientes))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloClientes)
                            .addComponent(lblSelect4)
                            .addGroup(pnlClientesLayout.createSequentialGroup()
                                .addComponent(btnRegistrarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrarCliente)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloClientes)
                .addGap(18, 18, 18)
                .addComponent(lblSelect4)
                .addGap(18, 18, 18)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCliente)
                    .addComponent(btnBorrarCliente))
                .addGap(18, 18, 18)
                .addComponent(scrollCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateTableClientes)
                .addGap(88, 88, 88))
        );

        tbdPanel.addTab("Clientes", pnlClientes);

        pnlTrabajadores.setBackground(new java.awt.Color(218, 223, 225));

        tituloTrabajadores.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        tituloTrabajadores.setText("Trabajadores:");

        lblSelect5.setText("Seleccione una opción");

        btnRegistrarTrabajador.setText("Registrar un trabajador");
        btnRegistrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrabajadorActionPerformed(evt);
            }
        });

        btnBorrarTrabajador.setText("Borrar trabajador");
        btnBorrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTrabajadorActionPerformed(evt);
            }
        });

        tblTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT Trabajador", "Nombre", "Apellido Paterno", "Direccion", "Telefono", "Correo", "Fecha Contrato"
            }
        ));
        scrollTrabajadores.setViewportView(tblTrabajadores);

        btnUpdateTableTrabajador.setText("Actualizar tabla");
        btnUpdateTableTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTrabajadoresLayout = new javax.swing.GroupLayout(pnlTrabajadores);
        pnlTrabajadores.setLayout(pnlTrabajadoresLayout);
        pnlTrabajadoresLayout.setHorizontalGroup(
            pnlTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(pnlTrabajadoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdateTableTrabajador))
                    .addGroup(pnlTrabajadoresLayout.createSequentialGroup()
                        .addGroup(pnlTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloTrabajadores)
                            .addComponent(lblSelect5)
                            .addGroup(pnlTrabajadoresLayout.createSequentialGroup()
                                .addComponent(btnRegistrarTrabajador)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrarTrabajador)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTrabajadoresLayout.setVerticalGroup(
            pnlTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTrabajadores)
                .addGap(18, 18, 18)
                .addComponent(lblSelect5)
                .addGap(18, 18, 18)
                .addGroup(pnlTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarTrabajador)
                    .addComponent(btnBorrarTrabajador))
                .addGap(18, 18, 18)
                .addComponent(scrollTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateTableTrabajador)
                .addGap(88, 88, 88))
        );

        tbdPanel.addTab("Trabajadores", pnlTrabajadores);

        logoFastDevelopment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgFolder/Logo/logo 256.png"))); // NOI18N

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logoFastDevelopment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tbdPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(logoFastDevelopment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tbdPanel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        //Go to Registrar Venta frame
        frameRegistrarVenta Frame = new frameRegistrarVenta();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnBorrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarVentaActionPerformed
        //Go to Borrar Venta frame
        frameBorrarVenta Frame = new frameBorrarVenta();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBorrarVentaActionPerformed

    private void btnRegistrarArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarArriendoActionPerformed
        //Registrar Arriendo
        frameRegistrarArriendo Frame = new frameRegistrarArriendo();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarArriendoActionPerformed

    private void btnBorrarArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarArriendoActionPerformed
        //Borrar un Arriendo
        frameBorrarArriendo Frame = new frameBorrarArriendo();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBorrarArriendoActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        //Registrar a un cliente
        frameRegistrarCliente Frame = new frameRegistrarCliente();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClienteActionPerformed
        //Go to borrar cliente
        frameBorrarCliente Frame = new frameBorrarCliente();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBorrarClienteActionPerformed

    private void btnRegistrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrabajadorActionPerformed
        //Go to registrar Trabajador frame
        frameRegistrarTrabajador Frame = new frameRegistrarTrabajador();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarTrabajadorActionPerformed

    private void btnBorrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTrabajadorActionPerformed
        //Go to borrar Trabajador
        frameBorrarTrabajador Frame = new frameBorrarTrabajador();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBorrarTrabajadorActionPerformed

    private void btnBorrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLibroActionPerformed
        //Go to Borrar Libro Frame
        frameBorrarLibro Frame = new frameBorrarLibro();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBorrarLibroActionPerformed

    private void btnRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibroActionPerformed
        //Init Frame Registrar Libro
        frameRegistrarLibro regLibro = new frameRegistrarLibro();
        regLibro.setVisible(true);
        regLibro.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarLibroActionPerformed

    private void btnBorrarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLibro1ActionPerformed
        //Go to Borrar ISBN Frame
        frameBorrarISBN Frame = new frameBorrarISBN();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBorrarLibro1ActionPerformed

    private void btnRegistrarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarLibro1ActionPerformed
        //Go to Registrar ISBN frame
        frameRegistrarISBN Frame = new frameRegistrarISBN();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarLibro1ActionPerformed

    private void btnUpdateISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateISBNActionPerformed
        try {
            DefaultTableModel tModel = (DefaultTableModel) tblISBN.getModel();
            //Clean table
            tModel.setRowCount(0);
            
            //Query
            String query = "SELECT * FROM ISBN";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            
            // create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);      // iterate through the java resultset
            while (rs.next())
            {
                String ISBN = rs.getString("ISBN");
                String categoria = rs.getString("CATEGORIA");
                String idioma = rs.getString("IDIOMA");
                String autor = rs.getString("AUTOR");
                String editorial = rs.getString("EDITORIAL");
                String titulo = rs.getString("TITULO");
                int numPaginas = rs.getInt("NUMERO_PAGINA");
                Date fechaPublicacion = rs.getDate("FECHA_PUBLICACION");
                
                //Fill the table with data
                Object[] fila = new Object[8];
                fila[0] = ISBN;
                fila[1] = titulo;
                fila[2] = autor;
                fila[3] = idioma;
                fila[4] = editorial;
                fila[5] = categoria;
                fila[6] = numPaginas;
                fila[7] = fechaPublicacion;
                tModel.addRow(fila);;
            }
            st.close();

            JOptionPane.showMessageDialog(null, "Tabla actualizada.");
        } catch (Exception e) {
            System.out.println("------------------");
            System.out.println("Got an Exception");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnUpdateISBNActionPerformed

    private void btnUpdateTableClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableClientesActionPerformed
        
        try {
            DefaultTableModel tModel = (DefaultTableModel) tblClientes.getModel();
            //Clean table
            tModel.setRowCount(0);
            
            //Query
            String query = "SELECT * FROM CLIENTE";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            
            // create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);      // iterate through the java resultset
            while (rs.next())
            {
                String rut = rs.getString("RUT_CLIENTE");
                String nombre = rs.getString("NOMBRE");
                String apellidoP = rs.getString("APELLIDO_PATERNO");
                String direccion = rs.getString("DIRECCION");
                String telefono = rs.getString("TELEFONO");
                String correo = rs.getString("CORREO");
                Date fechaNacimiento = rs.getDate("FECHA_NACIMIENTO");
                
                
                //Fill the table with data
                Object[] fila = new Object[8];
                fila[0] = rut;
                fila[1] = nombre;
                fila[2] = apellidoP;
                fila[3] = direccion;
                fila[4] = telefono;
                fila[5] = correo;
                fila[6] = fechaNacimiento;
                fila[7] = nombre;

                tModel.addRow(fila);;
            }
            st.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Tabla actualizada.");
        } catch (Exception e) {
            System.out.println("------------------");
            System.out.println("Got an Exception");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnUpdateTableClientesActionPerformed

    private void btnUpdateTableArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableArriendoActionPerformed
        
        try {
            DefaultTableModel tModel = (DefaultTableModel) tblArriendos.getModel();
            //Clean table
            tModel.setRowCount(0);
            
            //Query
            String query = "SELECT * FROM ARRIENDO";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            
            // create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);      // iterate through the java resultset
            while (rs.next())
            {
                int ID = rs.getInt("ID");
                int costoArriendo = rs.getInt("COSTO_ARRIENDO");
                Date fechaArriendo = rs.getDate("FECHA_ARRIENDO");
                String diasArriendo = rs.getString("DIAS_ARRENDADOS");
                Date fechaEntrega = rs.getDate("FECHA_ENTREGA");
                String rutCliente = rs.getString("FK_RUT_CLIENTE");
                String rutTrabajador = rs.getString("FK_RUT_TRABAJADOR");
                int numeroSerie = rs.getInt("FK_NUMERO_SERIE");
                
                
                //Fill the table with data
                Object[] fila = new Object[8];
                fila[0] = ID;
                fila[1] = "$ " + costoArriendo;
                fila[2] = fechaArriendo;
                fila[3] = diasArriendo;
                fila[4] = fechaEntrega;
                fila[5] = rutCliente;
                fila[6] = rutTrabajador;
                fila[7] = numeroSerie;
                tModel.addRow(fila);;
            }
            st.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Tabla actualizada.");
        } catch (Exception e) {
            System.out.println("------------------");
            System.out.println("Got an Exception");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnUpdateTableArriendoActionPerformed

    private void btnUpdateTableVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableVentasActionPerformed
        try {
            DefaultTableModel tModel = (DefaultTableModel) tblVentas.getModel();
            //Clean table
            tModel.setRowCount(0);
            
            //Query
            String query = "SELECT * FROM VENTA";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            
            // create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);      // iterate through the java resultset
            while (rs.next())
            {
                int ID = rs.getInt("ID");
                Date fechaVenta = rs.getDate("FECHA_VENTA");
                String numSerie = rs.getString("FK1_NUMERO_SERIE");
                String rutCliente = rs.getString("FK1_RUT_CLIENTE");
                String rutTrabajador = rs.getString("FK1_RUT_TRABAJADOR");
                
                
                //Fill the table with data
                Object[] fila = new Object[5];
                fila[0] = ID;
                fila[1] = fechaVenta;
                fila[2] = numSerie;
                fila[3] = rutCliente;
                fila[4] = rutTrabajador;
                
                tModel.addRow(fila);;
            }
            st.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Tabla actualizada.");
            
        } catch (Exception e) {
            System.out.println("------------------");
            System.out.println("Got an Exception");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnUpdateTableVentasActionPerformed

    private void btnUpdateTableLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableLibrosActionPerformed
        try {
            DefaultTableModel tModel = (DefaultTableModel) tblLibros.getModel();
            //Clean table
            tModel.setRowCount(0);
            
            //Query
            String query = "SELECT * FROM LIBRO";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            
            // create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);      // iterate through the java resultset
            while (rs.next())
            {
                int numSerie = rs.getInt("NUMERO_SERIE");
                int precio = rs.getInt("PRECIO");
                int precioIVA = rs.getInt("PRECIO_IVA");
                String distribuidor = rs.getString("DISTRIBUIDOR");
                String ISBN = rs.getString("ISBN_FK");
                
                
                //Fill the table with data
                Object[] fila = new Object[6];
                fila[0] = numSerie;
                fila[1] = "$ " + precio;
                fila[2] = "$ " + precioIVA;
                fila[3] = distribuidor;
                fila[4] = ISBN;
                fila[5] = "$ " + precio + precioIVA;
                tModel.addRow(fila);;
            }
            st.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Tabla actualizada.");
        } catch (Exception e) {
            System.out.println("------------------");
            System.out.println("Got an Exception");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnUpdateTableLibrosActionPerformed

    private void btnUpdateTableTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableTrabajadorActionPerformed
        try {
            DefaultTableModel tModel = (DefaultTableModel) tblTrabajadores.getModel();
            //Clean table
            tModel.setRowCount(0);
            
            //Query
            String query = "SELECT * FROM TRABAJADOR";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            
            // create the java statement
            Statement st = conn.createStatement();
            // execute the query, and get a java resultset
            ResultSet rs = st.executeQuery(query);      // iterate through the java resultset
            while (rs.next())
            {
                String rut = rs.getString("RUT_TRABAJADOR");
                String nombre = rs.getString("NOMBRE");
                String apellidoP = rs.getString("APELLIDO_PATERNO");
                String direccion = rs.getString("DIRECCION");
                String telefono = rs.getString("TELEFONO");
                String correo = rs.getString("CORREO");
                Date fechaContrato = rs.getDate("FECHA_CONTRATO");
                
                
                //Fill the table with data
                Object[] fila = new Object[7];
                fila[0] = rut;
                fila[1] = nombre;
                fila[2] = apellidoP;
                fila[3] = direccion;
                fila[4] = telefono;
                fila[5] = correo;
                fila[6] = fechaContrato;

                tModel.addRow(fila);;
            }
            st.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Tabla actualizada.");
            
        } catch (Exception e) {
            System.out.println("------------------");
            System.out.println("Got an Exception");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnUpdateTableTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBorrarArriendo;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnBorrarLibro;
    private javax.swing.JButton btnBorrarLibro1;
    private javax.swing.JButton btnBorrarTrabajador;
    private javax.swing.JButton btnBorrarVenta;
    private javax.swing.JButton btnRegistrarArriendo;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarLibro;
    private javax.swing.JButton btnRegistrarLibro1;
    private javax.swing.JButton btnRegistrarTrabajador;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JButton btnUpdateISBN;
    private javax.swing.JButton btnUpdateTableArriendo;
    private javax.swing.JButton btnUpdateTableClientes;
    private javax.swing.JButton btnUpdateTableLibros;
    private javax.swing.JButton btnUpdateTableTrabajador;
    private javax.swing.JButton btnUpdateTableVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblSelect2;
    private javax.swing.JLabel lblSelect3;
    private javax.swing.JLabel lblSelect4;
    private javax.swing.JLabel lblSelect5;
    private javax.swing.JLabel logoFastDevelopment;
    private javax.swing.JPanel mainpnlLibros;
    private javax.swing.JPanel pnlArriendo;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlISBN;
    private javax.swing.JTabbedPane pnlInner;
    private javax.swing.JPanel pnlOptionsLibro;
    private javax.swing.JPanel pnlTrabajadores;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JScrollPane scrollArriendo;
    private javax.swing.JScrollPane scrollCliente;
    private javax.swing.JScrollPane scrollLibros;
    private javax.swing.JScrollPane scrollLibros1;
    private javax.swing.JScrollPane scrollTrabajadores;
    private javax.swing.JScrollPane scrollVentas;
    private javax.swing.JTabbedPane tbdPanel;
    private javax.swing.JTable tblArriendos;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblISBN;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTable tblTrabajadores;
    private javax.swing.JTable tblVentas;
    private javax.swing.JLabel tituloArriendos;
    private javax.swing.JLabel tituloClientes;
    private javax.swing.JLabel tituloLibros;
    private javax.swing.JLabel tituloTrabajadores;
    private javax.swing.JLabel tituloVentas;
    // End of variables declaration//GEN-END:variables
}
