/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.popUps.Libros.Registrar.ISBN;

import UI.main.Conexion;
import UI.main.mainFrame;
import UI.popUps.Libros.Registrar.Libro.frameRegistrarLibro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author momo
 */
public class frameRegistrarISBN extends javax.swing.JFrame {

    /**
     * Creates new form frameRegistrarLibro
     */
    public frameRegistrarISBN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblTituloLibro = new javax.swing.JLabel();
        lblPaginasLibro = new javax.swing.JLabel();
        lblAñoPublicacion = new javax.swing.JLabel();
        cbxDay = new javax.swing.JComboBox<>();
        cbxMonth = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnConfirmarRegistro = new javax.swing.JButton();
        lblDatosAvanzados = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblAñoPublicacion3 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        cbxIdioma = new javax.swing.JComboBox<>();
        cbxEditorial = new javax.swing.JComboBox<>();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblEditorial1 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(46, 49, 49));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setLabelFor(txtTitulo);
        lblTitulo.setText("Registrar ISBN");

        lblTituloLibro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTituloLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLibro.setText("Título:");

        lblPaginasLibro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPaginasLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblPaginasLibro.setText("Páginas");

        lblAñoPublicacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAñoPublicacion.setForeground(new java.awt.Color(255, 255, 255));
        lblAñoPublicacion.setText("Fecha publicacion:");

        cbxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDayActionPerformed(evt);
            }
        });

        cbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMonthActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtPaginas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasActionPerformed(evt);
            }
        });

        txtYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtYear.setToolTipText("Ingrese el Año");
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        btnConfirmarRegistro.setText("Confirmar registro");
        btnConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRegistroActionPerformed(evt);
            }
        });

        lblDatosAvanzados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDatosAvanzados.setForeground(new java.awt.Color(255, 255, 255));
        lblDatosAvanzados.setText("Datos avanzados");

        lblIsbn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIsbn.setForeground(new java.awt.Color(255, 255, 255));
        lblIsbn.setText("Codigo ISBN:");

        lblIdioma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(255, 255, 255));
        lblIdioma.setText("Idioma:");

        lblCategoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText("Categoría:");

        lblEditorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEditorial.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorial.setText("Editorial:");

        lblAñoPublicacion3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAñoPublicacion3.setForeground(new java.awt.Color(255, 255, 255));
        lblAñoPublicacion3.setText("(Día / Mes / Año)");

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        cbxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccion un idioma", "Español", "Ingles", "Frances", "Italiano", "Portugues" }));

        cbxEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una editorial", "Casa amarilla", "Zig-Zag", "Ocho libros", "Nueva vida", "America libros" }));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría", "Horror", "Amor", "Comedia", "Historia", "Fantasía" }));

        lblEditorial1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEditorial1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorial1.setText("Autor:");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEditorial))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(lblDatosAvanzados)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmarRegistro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                        .addComponent(lblAñoPublicacion)
                                        .addGap(16, 16, 16)
                                        .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPaginasLibro)
                                            .addComponent(lblTituloLibro)
                                            .addComponent(lblIsbn)
                                            .addComponent(lblCategoria)
                                            .addComponent(lblAñoPublicacion3)
                                            .addComponent(lblIdioma))
                                        .addGap(21, 21, 21)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTitulo)
                                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbxCategoria, 0, 182, Short.MAX_VALUE)
                                                .addComponent(cbxIdioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxEditorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtAutor))
                                            .addComponent(txtISBN))))
                                .addGap(18, 18, 18)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditorial1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(329, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloLibro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaginasLibro))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAñoPublicacion)
                    .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblAñoPublicacion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatosAvanzados)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdioma)
                    .addComponent(cbxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorial)
                    .addComponent(cbxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorial1)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnConfirmarRegistro))
                .addContainerGap())
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Back to main Frame
        mainFrame mainF = new mainFrame();
        mainF.setVisible(true);
        mainF.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void cbxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMonthActionPerformed

    private void btnConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRegistroActionPerformed
        boolean send = true;
        
        String titulo = txtTitulo.getText();
        String paginas = txtPaginas.getText();
        
        String fechaD = cbxDay.getSelectedItem().toString();
        String fechaM = cbxMonth.getSelectedItem().toString();
        String fechaY = txtYear.getText();
        
        String ISBN = txtISBN.getText();
        
        String idioma = cbxIdioma.getSelectedItem().toString();
        String categoria = cbxCategoria.getSelectedItem().toString();
        String editorial = cbxEditorial.getSelectedItem().toString();
        String autor = txtAutor.getText();
        
        
        //Verificacion de fechas y numeros
        try {
            int intPaginas = Integer.parseInt(paginas);
            if(intPaginas >= 2000){
                JOptionPane.showMessageDialog(null, "No se pueden exceder las 2000 páginas.");
                send = false;
            }
            else if(intPaginas <= 0){
                JOptionPane.showMessageDialog(null, "Numero de páginas no puede ser negativo igual a 0.");
                send = false;
            }
            //Verificacion de fecha
            int intFechaY = Integer.parseInt(fechaY);
            //Current Date
            Date date = new Date();  
            SimpleDateFormat currentY = new SimpleDateFormat("yyyy"); 
            int intCurrentY = Integer.parseInt(currentY.format(date));
            if(intFechaY > intCurrentY){
                JOptionPane.showMessageDialog(null, "Año mal ingresado.");
                System.out.println("Año mal ingresado.");
                send = false;
            }   
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
            send =false;
        }
        
        
        
        
        //Verificacion de CBX FECHA DIA
        if(fechaD.equalsIgnoreCase("seleccione un dia")){
            System.out.println("Dia mal ingresado.");
            send = false;
        }
        //Verificacion de CBX FECHA MES
        if(fechaM.equalsIgnoreCase("seleccione un mes")){
            System.out.println("Mes mal ingresado.");
            send = false;
        }
        //Verificacion de CBX IDIOMA
        if(idioma.equalsIgnoreCase("seleccione un idioma")){
            System.out.println("Idioma mal ingresado.");
            send = false;
        }
        //Verificacion de CBX CATEGORIA
        if(categoria.equalsIgnoreCase("seleccione una categoria")){
            System.out.println("Categoria mal ingresada.");
            send = false;
        }
        //Verificacion de CBX EDITORIAL
        if(editorial.equalsIgnoreCase("seleccione una editorial")){
            System.out.println("Editorial mal ingresada.");
            send = false;
        }
        
        
        
        //Verificacion de casillas rellenadas
        if(titulo.equalsIgnoreCase("")){
            send = false;
        }
        if(paginas.equalsIgnoreCase("")){
            send = false;
        }
        if(fechaY.equalsIgnoreCase("")){
            send = false;
        }
        if(ISBN.equalsIgnoreCase("")){
            send = false;
        }
        if(idioma.equalsIgnoreCase("")){
            send = false;
        }
        if(categoria.equalsIgnoreCase("")){
            send = false;
        }
        if(editorial.equalsIgnoreCase("")){
            send = false;
        }
        if(autor.equalsIgnoreCase("")){
            send = false;
        }
        
        //ISBN CODE
        if(ISBN.length() != 10){
            JOptionPane.showMessageDialog(null, "ISBN Debe ser de 10 digitos.");
            System.out.println("ISBN LEN : " + ISBN.length() );
            send = false;
        }


        if(send){  
            try {  
                //Query
                //Hacer la conexion aqui abajo
                System.out.println("PRINT VALUES:");
                System.out.println("-------------------");
                System.out.println("ISBN " + ISBN);
                System.out.println("titulo: " + titulo);
                System.out.println("Paginas: " + paginas);
                System.out.println("Fecha: " + fechaY + "-" + fechaM + "-" + fechaD);
                System.out.println("Categoria: " + categoria);
                System.out.println("Idioma:" + idioma);
                System.out.println("Autor: " + autor);
                System.out.println("Editorial: " + editorial);
                System.out.println("");
                
                String query = " INSERT INTO ISBN(ISBN, CATEGORIA, IDIOMA, AUTOR, EDITORIAL, TITULO, NUMERO_PAGINA, FECHA_PUBLICACION)"
                        + " values(?, ?, ?, ?, ?, ?, ?, ?)";
                
                Conexion conector = new Conexion();
                Connection conn = conector.conectar();
                try {
                    PreparedStatement preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1, ISBN);
                    preparedStmt.setString(2, categoria);
                    preparedStmt.setString(3, idioma);
                    preparedStmt.setString(4, autor);
                    preparedStmt.setString(5, editorial);
                    preparedStmt.setString(6, titulo);
                    preparedStmt.setString(7, paginas);
                    preparedStmt.setString(8, fechaY + "-" + fechaM + "-" + fechaD);
                    
                    preparedStmt.execute();
                    conn.close();
                    preparedStmt.close();
                    JOptionPane.showMessageDialog(null, "Acción realizada con exito.");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Fatal ERROR.");
                    System.out.println("ERROR: " + e.toString());
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error de conexion.");
                Logger.getLogger(frameRegistrarISBN.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        //Error en las casillas.
        else{
            JOptionPane.showMessageDialog(null, "Casillas mal rellenadas.");
            System.out.println("ERROR: No se concretó la conexion.");
        }
    }//GEN-LAST:event_btnConfirmarRegistroActionPerformed

    private void cbxDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDayActionPerformed

    private void txtPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameRegistrarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnConfirmarRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxDay;
    private javax.swing.JComboBox<String> cbxEditorial;
    private javax.swing.JComboBox<String> cbxIdioma;
    private javax.swing.JComboBox<String> cbxMonth;
    private javax.swing.JLabel lblAñoPublicacion;
    private javax.swing.JLabel lblAñoPublicacion3;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDatosAvanzados;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblEditorial1;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblPaginasLibro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtPaginas;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
