/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.popUps.Trabajadores.Registrar;

import UI.main.Conexion;
import UI.main.mainFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author momo
 */
public class frameRegistrarTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form frameBorrarTrabajador
     */
    public frameRegistrarTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblGuia1 = new javax.swing.JLabel();
        lblNumeroSerie = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        btnConfirmarModificacion = new javax.swing.JButton();
        lblGuia2 = new javax.swing.JLabel();
        lblImportante = new javax.swing.JLabel();
        lblNumeroSerie1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        lblNumeroSerie2 = new javax.swing.JLabel();
        lblNumeroSerie3 = new javax.swing.JLabel();
        lblNumeroSerie4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblNumeroSerie5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblNumeroSerie6 = new javax.swing.JLabel();
        lblGuia3 = new javax.swing.JLabel();
        lblGuia4 = new javax.swing.JLabel();
        cbxPrefijo = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(46, 49, 49));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registrar Trabajador:");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblGuia1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGuia1.setForeground(new java.awt.Color(255, 255, 255));
        lblGuia1.setText("Para poder eliminar a un Trabajador se requiere su RUT.");

        lblNumeroSerie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie.setText("RUT Trabajador:");

        btnConfirmarModificacion.setText("Confirmar registro");
        btnConfirmarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarModificacionActionPerformed(evt);
            }
        });

        lblGuia2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGuia2.setForeground(new java.awt.Color(255, 255, 255));
        lblGuia2.setText("- La fecha de contraro se generará automáticamente.");

        lblImportante.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblImportante.setForeground(new java.awt.Color(255, 255, 255));
        lblImportante.setText("Importante:");

        lblNumeroSerie1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie1.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie1.setText("Nombre:");

        lblNumeroSerie2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie2.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie2.setText("Apellido Paterno:");

        lblNumeroSerie3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie3.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie3.setText("Apellido Materno:");

        lblNumeroSerie4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie4.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie4.setText("Direccion:");

        lblNumeroSerie5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie5.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie5.setText("Teléfono:");

        lblNumeroSerie6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNumeroSerie6.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie6.setText("Correo electrónico:");

        lblGuia3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGuia3.setForeground(new java.awt.Color(255, 255, 255));
        lblGuia3.setText("  en nuestra Base de Datos luego de confirmar el registro.");

        lblGuia4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGuia4.setForeground(new java.awt.Color(255, 255, 255));
        lblGuia4.setText("- El teléfono y el correo electrónico serán registrados");

        cbxPrefijo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+56", "+591", "+55", "+57", "+593", "+596", "+51" }));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuia1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImportante, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuia2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(163, 163, 163)
                                .addComponent(btnConfirmarModificacion)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNumeroSerie)
                                            .addComponent(lblNumeroSerie1))
                                        .addGap(78, 78, 78)
                                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre)
                                            .addComponent(txtRut)))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(lblNumeroSerie4)
                                        .addGap(306, 306, 306)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroSerie2)
                                    .addComponent(lblNumeroSerie3)
                                    .addComponent(lblNumeroSerie5)
                                    .addComponent(lblNumeroSerie6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtApellidoM)
                                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(cbxPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTelefono)))))
                        .addContainerGap())
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGuia4)
                            .addComponent(lblGuia3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblGuia1)
                .addGap(18, 18, 18)
                .addComponent(lblImportante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGuia2)
                .addGap(18, 18, 18)
                .addComponent(lblGuia4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGuia3)
                .addGap(35, 35, 35)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie2)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie3)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNumeroSerie5))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie6)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnConfirmarModificacion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Back to MAIN Frame
        mainFrame Frame = new mainFrame();
        Frame.setVisible(true);
        Frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarModificacionActionPerformed
        boolean send = true;
        
        String rut = txtRut.getText();
        String nombre = txtNombre.getText();
        String apellidoP = txtApellidoP.getText();
        String apellidoM = txtApellidoM.getText();
        String direccion = txtDireccion.getText();
        String prefijo = cbxPrefijo.getSelectedItem().toString();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        
        try {
            SimpleDateFormat formatY = new SimpleDateFormat("yyyy"); 
            SimpleDateFormat formatM = new SimpleDateFormat("MM");
            SimpleDateFormat formatD = new SimpleDateFormat("dd");
            
            
            //Generacion de fecha actual.
            Date date = new Date();
            String currentY = formatY.format(date);
            String currentM = formatD.format(date);
            String currentD = formatM.format(date);

            
            //Verificaciones de casillas INPUT
            if(rut.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un RUT");
                System.out.println("RUT no ingresado");
                send = false;
            }
            if(nombre.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un Nombre");
                System.out.println("Nombre no ingresado");
                send = false;
            }
            if(apellidoP.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un Apellido Paterno");
                System.out.println("Apellido Paterno no ingresado");
                send = false;
            }
            if(apellidoM.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un Apellido Materno");
                System.out.println("Apellido Materno no ingresado");
                send = false;
            }
            if(direccion.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese una Direccion");
                System.out.println("Direccion no ingresada");
                send = false;
            }
            if(telefono.equalsIgnoreCase("") || telefono.length() != 9){
                JOptionPane.showMessageDialog(null, "Ingrese un número de 9 dígitos.");
                System.out.println("Telefono ingresado incorrectamente.");
                send = false;
            }
            if(correo.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Ingrese un correo electrónico");
                System.out.println("Correo Electrónico ingresado incorrectamente.");
                send = false;
            }
            
            
            //Conexion a BDD
            if(send){
                //concatenacion telefono
                String tel = prefijo + telefono;    //CONCATENACION DEL PREFIJO Y EL TELEFONO INGRESADO
                String fechaNacimiento  =  currentY + "-" + currentM + "-" + currentD ;
                
                
                //Datos cargados del input
                System.out.println("DATOS CARGADOS:");
                System.out.println("-------------");
                System.out.println("RUT Cliente: " + rut);
                System.out.println("Nombre: " + nombre);
                System.out.println("Apellido Paterno: " + apellidoP);
                System.out.println("Apellido Materno: " + apellidoM);
                System.out.println("Direccion: " + direccion);
                System.out.println("telefono: " + tel); //OJO ACA QUE NO SON LAS PRIMERAS VARIABLES, ES UNA CONCATENACION
                System.out.println("Correo electronico: " + correo);
                System.out.println("Fecha de contrato: " + fechaNacimiento);
            
           //Conexion a la BD
            String query = " INSERT INTO TRABAJADOR(RUT_TRABAJADOR, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, DIRECCION,"
                    + "TELEFONO, CORREO, FECHA_CONTRATO)"
                    + " values(?, ?, ?, ?, ?, ?, ?, ?)";
            
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            try {
                    PreparedStatement preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1, rut);
                    preparedStmt.setString(2, nombre);
                    preparedStmt.setString(3, apellidoP);
                    preparedStmt.setString(4, apellidoM);
                    preparedStmt.setString(5, direccion);
                    preparedStmt.setString(6, tel);
                    preparedStmt.setString(7, correo);
                    preparedStmt.setString(8, currentY + "-" + currentM + "-" + currentD);


                    preparedStmt.execute();
                    conn.close();
                    preparedStmt.close();
                    JOptionPane.showMessageDialog(null, "Acción realizada con exito.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fatal ERROR.");
            System.out.println("ERROR: " + e.toString());
        }
            
            }
            else{
                JOptionPane.showMessageDialog(null, "Casillas mal rellenadas.");
                System.out.println("------------------------");
                System.out.println("Casillas mal rellenadas");
                System.out.println("------------------------");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fatal Error.");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnConfirmarModificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameRegistrarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnConfirmarModificacion;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxPrefijo;
    private javax.swing.JLabel lblGuia1;
    private javax.swing.JLabel lblGuia2;
    private javax.swing.JLabel lblGuia3;
    private javax.swing.JLabel lblGuia4;
    private javax.swing.JLabel lblImportante;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblNumeroSerie1;
    private javax.swing.JLabel lblNumeroSerie2;
    private javax.swing.JLabel lblNumeroSerie3;
    private javax.swing.JLabel lblNumeroSerie4;
    private javax.swing.JLabel lblNumeroSerie5;
    private javax.swing.JLabel lblNumeroSerie6;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
