/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.popUps.Libros.Registrar.Libro;

import UI.main.Conexion;
import UI.main.mainFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author momo
 */
public class frameRegistrarLibro extends javax.swing.JFrame {

    /**
     * Creates new form frameRegistrarLibro
     */
    public frameRegistrarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnConfirmarRegistro = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblPrecioLibro = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblNumeroSerie = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        lblIsbn = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblDistribuidor = new javax.swing.JLabel();
        lblEstadoLibro = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        cbxDistribuidor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(46, 49, 49));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarRegistro.setText("Confirmar registro");
        btnConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRegistroActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Registrar Libro");

        lblPrecioLibro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPrecioLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioLibro.setText("Precio:");

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblNumeroSerie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroSerie.setText("Numero de serie:");

        lblIsbn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIsbn.setForeground(new java.awt.Color(255, 255, 255));
        lblIsbn.setText("Codigo ISBN:");

        lblDistribuidor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDistribuidor.setForeground(new java.awt.Color(255, 255, 255));
        lblDistribuidor.setText("Nombre del distribuidor:");

        lblEstadoLibro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEstadoLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoLibro.setText("Estado del libro:");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado actual del libro", "Vendido", "Arrendado", "Disponible" }));
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        cbxDistribuidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Distribuidor", "Distribuidora R C A", "Distribuidora de Material Didactico", "Distribuidor Libros y Revistas", "SOC Importadora", "Kuatro Libros" }));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarRegistro)
                        .addContainerGap())
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroSerie)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioLibro)
                                    .addComponent(lblEstadoLibro)
                                    .addComponent(lblIsbn)
                                    .addComponent(lblDistribuidor))
                                .addGap(29, 29, 29)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtISBN)
                                    .addComponent(txtNumeroSerie)
                                    .addComponent(txtPrecio)
                                    .addComponent(cbxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxDistribuidor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioLibro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroSerie)
                    .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistribuidor)
                    .addComponent(cbxDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoLibro)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //Back to main Frame
        mainFrame mainF = new mainFrame();
        mainF.setVisible(true);
        mainF.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRegistroActionPerformed
        boolean send = true;
        
        String precio = txtPrecio.getText();
        String numeroSerie = txtNumeroSerie.getText();
        String codigoISBN = txtISBN.getText();
        String distribuidor = cbxDistribuidor.getSelectedItem().toString();
        String estadoLibro = cbxEstado.getSelectedItem().toString();
        
        
        try {
            int intPrecio = Integer.parseInt(precio);
            int intNumeroSerie = Integer.parseInt(numeroSerie);
            
            //Valor del IVA
            double precioIVA = intPrecio * 0.19;

        
        //Verificacion de casillas
        if(codigoISBN.equalsIgnoreCase("")){
            System.out.println("INPUT txtISBN no rellenado");
            send = false;
        }else if(codigoISBN.length() != 10){
            JOptionPane.showMessageDialog(null, "Código ISBN debe ser de 10 numeros.");
        }
        
        if(distribuidor.equalsIgnoreCase("seleccione un distribuidor")){
            System.out.println("Nombre del distribuidor no seleccionado.");
            JOptionPane.showMessageDialog(null, "Seleccione un distribuidor.");
            send = false;
        }
        if(estadoLibro.equalsIgnoreCase("estado actual del libro")){
            System.out.println("Estado del libro no seleccionado");
            JOptionPane.showMessageDialog(null, "Seleccione un Estado del libro.");
            send = false;
        }
        
        //AQUI ABAJO HAZ LA CONEXION A LA BDD
        if(send){
            
            //Datos cargados del input
            System.out.println("");
            System.out.println("-------------------------------");
            System.out.println("DATOS CARGADOS:");
            System.out.println("-------------------------------");
            System.out.println("Numero serie: " + numeroSerie);
            System.out.println("Precio: $" + precio);
            System.out.println("IVA: $" + precioIVA);
            System.out.println("Distribuidor: " + distribuidor);
            System.out.println("Estado del Libro: " + estadoLibro);
            System.out.println("Codigo ISBN: " + codigoISBN);
            
            
           //Conexion a la BD
            String query = " INSERT INTO LIBRO(NUMERO_SERIE, PRECIO, PRECIO_IVA, DISTRIBUIDOR, ESTADO, ISBN_FK)"
                    + " values(?, ?, ?, ?, ?, ?)";
        
            Conexion conector = new Conexion();
            Connection conn = conector.conectar();
            try {
             PreparedStatement preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setInt(1, intNumeroSerie);
                    preparedStmt.setInt(2, intPrecio);
                    preparedStmt.setDouble(3, precioIVA);
                    preparedStmt.setString(4, distribuidor);
                    preparedStmt.setString(5, estadoLibro);
                    preparedStmt.setString(6, codigoISBN);
                   

                    preparedStmt.execute();
                    conn.close();
                    preparedStmt.close();
                    JOptionPane.showMessageDialog(null, "Acción realizada con exito.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Fatal Error..");
                System.out.println("ERROR: " + e.toString());
            }
        
        
       
        }
        else{
            JOptionPane.showMessageDialog(null, "Casillas mal rellenadas.");
            System.out.println("------------------------");
            System.out.println("Casillas mal rellenadas");
            System.out.println("------------------------");
        }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fatal Error.'");
            System.out.println("ERROR: " + e.toString());
        }
    }//GEN-LAST:event_btnConfirmarRegistroActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameRegistrarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnConfirmarRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDistribuidor;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel lblDistribuidor;
    private javax.swing.JLabel lblEstadoLibro;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblPrecioLibro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
